CREATE TABLE `conversions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`conversionId` varchar(32) NOT NULL,
	`userId` int,
	`filename` varchar(512) NOT NULL,
	`pdfKey` varchar(1024),
	`pdfUrl` text,
	`markdownKey` varchar(1024),
	`markdownUrl` text,
	`markdownContent` text,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`totalPages` int,
	`figuresExtracted` int,
	`conversionMethod` varchar(64),
	`fileSize` bigint,
	`errorMessage` text,
	`images` json,
	`figureQuestionLinks` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `conversions_id` PRIMARY KEY(`id`),
	CONSTRAINT `conversions_conversionId_unique` UNIQUE(`conversionId`)
);
